Create Route and vue component for product CRUD Operation
1. Initiate Vue in Laravel: first we need to create a layouts folder inside the resources/views directory and then create an app.blade.php file.
2. Create Vue CRUD Components: we add app.vue inside resources js directory which will show menues and we initiate the router view here.  create app.vue file in resources/js folder.
3.  create products folder ‘procuts’ inside resources/js/components directory.
4. we create three component one index.vue which will list the produts, another is create.vue which will show the product create form and another is edit.vue which will use for edit the product.
-> index.vue
-> create.vue
-> edit.vue
5. Create Vue Routes for Laravel Vue CRUD: -> resources/js/routes.js file
6. Include Dependencies to app.js -> resources\js\app.js.

=> npm run watch
=> php artisan serve

If you getting Error: Cannot find module ‘webpack/lib/rules/DescriptionDataMatcherRulePlugin’ Require stack error message then you need to update your vue-loader

=> npm update vue-loader